Add numactl feature for mongo instances
bitnami/bitnami-docker-mongodb-sharded pull request #17
Opened 2021-07-16 13:47 UTC by F43RY

**Description of the change**
With this new feature is possible to execute mongod/s instances prefixed with "numactl --interleave=all"

**Benefits**
As described in [MongoDB production Notes](https://docs.mongodb.com/manual/administration/production-notes/#configuring-numa-on-linux) this feature allow to enable numactl if desidered

**Possible drawbacks**

Possible performances issue if enabled and not supported or viceversa
**Applicable issues**

**Additional information**

2021-07-19 07:44 UTC, javsalgar requested changes
Thank you so much! Changes required

2021-07-19 07:44 UTC, javsalgar commented on 4.4/debian-10/prebuildfs/opt/bitnami/scripts/libos.sh
> +            numactl --interleave=all "$@"
note that libos.sh is shared across all containers. Does it make sense to use numactl in the rest of the containers? It seems to me that it should go in libmongodb.sh instead, like in mongodb_execute or similar.

2021-07-19 07:44 UTC, javsalgar commented on 4.4/debian-10/rootfs/opt/bitnami/scripts/mongodb-env.sh
> +export NUMACTL="${NUMACTL:-false}"
Is there any use case where I wouldn't want to use numactl if possible?

2021-07-19 10:34 UTC, F43RY commented on 4.4/debian-10/prebuildfs/opt/bitnami/scripts/libos.sh
> +            numactl --interleave=all "$@"
OK, no problem.
I'm going to move modify to libmongodb.sh ASAP.

2021-07-19 10:41 UTC, F43RY commented on 4.4/debian-10/rootfs/opt/bitnami/scripts/mongodb-env.sh
> +export NUMACTL="${NUMACTL:-false}"
Hi,
according to [MongoDB Production notes](https://docs.mongodb.com/manual/administration/production-notes/#mongodb-and-numa-hardware):

> Running MongoDB on a system with Non-Uniform Memory Access (NUMA) can cause a number of operational problems, including slow performance for periods of time and high system process usage.

At the moment no automatism is checking if is possible to use numa on the machine so I think is better set a boolean that can (dis/en)able this feature accordingly.

2021-07-20 07:44 UTC, javsalgar commented on 4.4/debian-10/rootfs/opt/bitnami/scripts/mongodb-env.sh
> +export NUMACTL="${NUMACTL:-false}"
For consistency, I'd rather use `MONGODB_ENABLE_NUMACTL` as the variable name.

2021-07-20 08:59 UTC, F43RY commented on 4.4/debian-10/rootfs/opt/bitnami/scripts/mongodb-env.sh
> +export NUMACTL="${NUMACTL:-false}"
Done

2021-07-21 07:35 UTC, javsalgar requested changes
Thanks! Small change

2021-07-21 07:35 UTC, javsalgar commented on 4.4/debian-10/Dockerfile
> +#RUN mv /opt/bitnami/mongodb/bin/mongod /opt/bitnami/mongodb/bin/mongod_cmd && \
Could you remove these comments?

2021-07-21 07:50 UTC, F43RY commented on 4.4/debian-10/Dockerfile
> +#RUN mv /opt/bitnami/mongodb/bin/mongod /opt/bitnami/mongodb/bin/mongod_cmd && \
Done

2021-07-22 08:06 UTC, javsalgar commented on 4.4/debian-10/Dockerfile
> +#ENTRYPOINT [ "/usr/bin/tail", "-f", "/dev/null" ]
Please remove this one as well

2021-07-22 18:07 UTC, javsalgar commented
Thanks for the changes! I'll be in PTO until Tuesday. When I come back I'll proceed with the merging

2021-07-28 12:01 UTC, merged